ccflags-y += -Idrivers/media/platform/msm/camera_mlte5_v2
ccflags-y += -Idrivers/media/platform/msm/camera_mlte5_v2/sensor/io
ccflags-y += -Idrivers/media/platform/msm/camera_mlte5_v2/sensor/cci
obj-$(CONFIG_MSM_EEPROM) += msm_eeprom.o
